heat_template_version: 2013-05-23

description:
  template should spin up a single FC20 instance

parameters:
  myimagename:
    type: string
    label: myimagename
    description: cloud image to use for the instance
    default: "Fedora 20 (Heisenbug) (PVHVM)"
    hidden: false
  myhostname:
    type: string
    label: myhostname
    description: base hostname of the instance
    default: "jenkins0"
    hidden: false
    constraints:
      - allowed_pattern: "[a-z0-9]+"
        description: hostname must consist of lowercase characters and numbers only.
      - length: { min: 4, max: 8 }
        description: Hostname length must be between 6 and 8 characters.
  myadminpass:
    type: string
    label: myadminpass
    description: root password
    default: "h@d0uke3N"
    hidden: false
    constraints:
      - length: { min: 8 }
        description: Password should be at least 8 characters

resources:
  compute_instance:
    type: "Rackspace::Cloud::Server"
    properties:
      admin_pass: { get_param: myadminpass }
      flavor: 512MB Standard Instance
      image: { get_param: myimagename }
      name: { get_param: myhostname }
      personality: { 
        "/opt/raxapitest/7424base_bootstrap.sh": { get_file: ../support/7424base_bootstrap.sh },
        "/opt/raxapitest/jenkins_bootstrap.sh": { get_file: ../support/jenkins_bootstrap.sh }
      }
      user_data: |
            #!/bin/bash
            bash /opt/raxapitest/7424base_bootstrap.sh && \
            bash /opt/raxapitest/jenkins_bootstrap.sh;

outputs:
  public_ip:
    description: public IP of the deployed instance
    value: { get_attr: [compute_instance, accessIPv4] }
  instance_param_hostname:
    description: hostname according to the myhostname param
    value: { get_param: myhostname }
  instance_details:
    description: details of new instance
    value: { get_attr: [compute_instance, show] }
